name: Node CI

on: [push]

jobs:
  build:
      steps:
        - uses: actions/checkout@v2
        - name: npm install and build webpack
          runs-on: ubuntu-latest
          run: |
            npm install
            npm run build
        
        - uses: actions/upload-artifact@master
          name: webpack artifacts
          path: public/

  test:
    steps:
      - uses: actions/download-artifact@main
        needs: build
        with:
          name: webpack artifacts
          path: public
        strategy:
          matrix:
            os: [ubuntu-latest, windows-2016]
            node-version: [12.x, 14.x]
  
      
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
